### ISSUE TITLE
MultipleASE not working in Pipeline

### ISSUE THREAD

**Issue by QuasiLegendre** [neurodata/graspy#234]
## Expected Behavior
All intermediate steps of the graspy.embed.mase.MultipleASE class should be transformers and implement fit and transform or be the string 'passthrough'.

## Actual Behavior
All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' '<class 'graspy.embed.mase.MultipleASE'>' (type <class 'type'>) doesn't.

## Template Code
```GraSPy
    from sklearn.svm import SVC
    #SVL = SupervisedLearning([('mase', MultipleASE), ('svc', SVC)], plot_method=plotSVC)
    SVL = Pipeline([('mase', MultipleASE), ('svc', SVC)])
    SVL.set_params(mase__n_components=2, mase__algorithm='full', svc__gamma='scale', svc__kernel='linear').fit(undirected_sbms, labels_sbm)


```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "COSIE.py", line 50, in <module>
    SVL = SupervisedLearning([('mase', MultipleASE), ('svc', SVC)], plot_method=plotSVC)
  File "COSIE.py", line 5, in __init__
    super(SupervisedLearning, self).__init__(steps, memory, verbose)
  File "/home/quasi/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 135, in __init__
    self._validate_steps()
  File "/home/quasi/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 185, in _validate_steps
    "'%s' (type %s) doesn't" % (t, type(t)))
TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' '<class 'graspy.embed.mase.MultipleASE'>' (type <class 'type'>) doesn't

```

## Your Environment
* Python version: 3.7.1
* GraSPy version: 0.0.3

**Comment by QuasiLegendre** [comment]
Solved by myself.
