### ISSUE TITLE
install issue with numba

### ISSUE THREAD

**Issue by hhelm10** [neurodata/graspy#407]
## Expected Behavior
install graspy

## Actual Behavior
process exited
(from what I can tell it's an issue related to `hyppo`s numba dependency)

## Template Code
```
pip3 install graspy

```

## Full Traceback
``` 
Collecting graspy
Collecting hyppo>=0.1.3 (from graspy)
Collecting scikit-learn>=0.19.1 (from graspy)
  Using cached https://files.pythonhosted.org/packages/5c/a1/273def87037a7fb010512bbc5901c31cfddfca8080bc63b42b26e3cc55b3/scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting matplotlib>=3.0.0 (from graspy)
  Using cached https://files.pythonhosted.org/packages/96/a7/b6fa244fd8a8814ef9408c8a5a7e4ed0340e232a6f0ce2046b42e50672c0/matplotlib-3.3.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting networkx>=2.1 (from graspy)
  Using cached https://files.pythonhosted.org/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl
Collecting seaborn>=0.9.0 (from graspy)
  Using cached https://files.pythonhosted.org/packages/c7/e6/54aaaafd0b87f51dfba92ba73da94151aa3bc179e5fe88fc5dfb3038e860/seaborn-0.10.1-py3-none-any.whl
Collecting numpy>=1.8.1 (from graspy)
  Using cached https://files.pythonhosted.org/packages/22/e7/4b2bdddb99f5f631d8c1de259897c2b7d65dcfcc1e0a6fd17a7f62923500/numpy-1.19.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=1.1.0 (from graspy)
  Using cached https://files.pythonhosted.org/packages/2b/a8/f4c66eb529bb252d50e83dbf2909c6502e2f857550f22571ed8556f62d95/scipy-1.5.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting numba>=0.46 (from hyppo>=0.1.3->graspy)
Collecting joblib>=0.11 (from scikit-learn>=0.19.1->graspy)
  Using cached https://files.pythonhosted.org/packages/51/dd/0e015051b4a27ec5a58b02ab774059f3289a94b0906f880a3f9507e74f38/joblib-0.16.0-py3-none-any.whl
Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.19.1->graspy)
  Using cached https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Collecting certifi>=2020.06.20 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pillow>=6.2.0 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/30/bf/92385b4262178ca22b34f82e0e09c2922eb351fe39f3cc7b8ba9ea555b41/Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/ae/23/147de658aabbf968324551ea22c0c13a00284c4ef49a77002e91f79657b7/kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting decorator>=4.3.0 (from networkx>=2.1->graspy)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting pandas>=0.22.0 (from seaborn>=0.9.0->graspy)
  Using cached https://files.pythonhosted.org/packages/a1/c6/9ac4ae44c24c787a1738e5fb34dd987ada6533de5905a041aa6d5bea4553/pandas-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting setuptools (from numba>=0.46->hyppo>=0.1.3->graspy)
  Using cached https://files.pythonhosted.org/packages/c3/a9/5dc32465951cf4812e9e93b4ad2d314893c2fa6d5f66ce5c057af6e76d85/setuptools-49.6.0-py3-none-any.whl
Collecting llvmlite<0.35,>=0.34.0.dev0 (from numba>=0.46->hyppo>=0.1.3->graspy)
  Using cached https://files.pythonhosted.org/packages/0b/96/07bfa93a103fb9e3e9ae7f9f7c6687ae714aee66b6f3000da3fad71e0aa2/llvmlite-0.34.0.tar.gz
Collecting six (from cycler>=0.10->matplotlib>=3.0.0->graspy)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pytz>=2017.2 (from pandas>=0.22.0->seaborn>=0.9.0->graspy)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite: started
  Running setup.py bdist_wheel for llvmlite: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ogxz66p6/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkn1dbrsjpip-wheel- --python-tag cp36:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: setuptools, llvmlite, numpy, numba, joblib, scipy, threadpoolctl, scikit-learn, hyppo, certifi, pyparsing, six, cycler, pillow, python-dateutil, kiwisolver, matplotlib, decorator, networkx, pytz, pandas, seaborn, graspy
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ogxz66p6/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-t6wf4b_5-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    got version from file /tmp/pip-build-ogxz66p6/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-ogxz66p6/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    
    ----------------------------------------
```

* Python version: 3.6.9
* GraSPy version: 0.3.0

**Comment by bdpedigo** [comment]
@sampan501 before we look into this, are you aware of this issue already? looks like it is upstream of you maybe but probably worth knowing about

@hhelm10 one thing you can try is installing a version of numba that is 1 or 2 versions old (they just released a new one) but I don't know if that is related. maybe it's worth starting a clean environment, and literally just try to install numba, and see what happens?

**Comment by sampan501** [comment]
It looks like an issue upstream of me. I can testing which ones work properly and just limit installation to that version

**Comment by bdpedigo** [comment]
@hhelm10 are you running on a Raspberry PI https://github.com/numba/llvmlite/issues/604 🤣 

But srsly, I bet that issue can help you out. My guess is that this issue is specific to whatever platform/environment you have going, so may be hard for us to help debug. lmk if the comments on that issue help, or how the clean environment numba install goes?

**Comment by hhelm10** [comment]
I'll take a look and will let you know how I end up fixing it!

Thanks guys @bdpedigo @sampan501

**Comment by j1c** [comment]
https://github.com/numba/numba/issues/6174

@hhelm10 what your pip version?

**Comment by hhelm10** [comment]
9.0.1!

**Comment by bdpedigo** [comment]
did u just say `9`

**Comment by j1c** [comment]
> 9.0.1!

:frowning:

**Comment by sampan501** [comment]
> 9.0.1!

You know the latest one's like 20 right?

**Comment by hhelm10** [comment]
Interesting; working from a new Azure VM. Upgraded to 20.2.2 and install worked with no problems.
